spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security6
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

jwt.signing.key: "f1da3383157397f4840b512b462ac11e363f6905233e4c242d6294f4f627d45619d7674585ce35d7afabff6f996d8a28430923f0f5a97699f240d125734aa71e"